# Generated by Django 4.1 on 2022-10-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('userId', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='아이디')),
                ('passwd', models.CharField(max_length=50, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('gender', models.CharField(max_length=6, verbose_name='성별')),
                ('address', models.CharField(max_length=500, null=True, verbose_name='주소')),
                ('detailaddr', models.CharField(max_length=500, null=True, verbose_name='디테일주소')),
                ('zonecode', models.CharField(max_length=5, null=True, verbose_name='우편번호')),
                ('email', models.CharField(max_length=500, null=True, verbose_name='이메일')),
                ('tel', models.CharField(max_length=30, null=True, unique=True, verbose_name='전화번호')),
                ('signupdate', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('modifydate', models.DateTimeField(auto_now_add=True, verbose_name='최근 수정일')),
                ('status', models.CharField(max_length=500, verbose_name='가입상태')),
            ],
        ),
    ]
